version: "3.9"
services:

  node-application:
    build: .
    container_name: node-application
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always


  presidio:
    image: ghcr.io/data-privacy-stack/presidio-analyzer:latest
    # ports:
    #   - "5002:3000"